### ISSUE TITLE
[Bug] Fee Swap not working

### ISSUE THREAD

**Issue by wuniversales** [CavernPerson/webapp#4]
The url is not working
Please, changue this...
`https://phoenix-fcd.terra.dev//v1/txs/gas_prices`
For
`https://phoenix-fcd.terra.dev/v1/txs/gas_prices`

**Comment by wuniversales** [comment]
I'm not sure if it's a bug, now it doesn't seem to happen.
If it happens again I'll let you know, I'll close this.

**Comment by CavernPerson** [comment]
Thanks, it fixed it
